Repository j-seon/yumyums, pull requests merged in 2024-08, with the labels that each got.

#64 이미지 업로더 모듈
  .gitignore
  src/main/java/com/yum/yumyums/controller/StoreController.java
  src/main/java/com/yum/yumyums/dto/ImagesDTO.java
  src/main/java/com/yum/yumyums/dto/seller/StoreDTO.java
  src/main/java/com/yum/yumyums/entity/Images.java
  src/main/java/com/yum/yumyums/entity/seller/Store.java
  src/main/java/com/yum/yumyums/repository/ImagesRepository.java
  src/main/java/com/yum/yumyums/service/ImagesService.java
  src/main/java/com/yum/yumyums/service/ImagesServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/StoreServiceImpl.java
  src/main/java/com/yum/yumyums/util/ImageDefaultUrl.java
  src/main/resources/static/img/yumyums_default.jpg
  src/main/resources/templates/store/list.html
  src/main/resources/templates/store/save.html
Labels: Plz review

#67 매출 데이터 분석 테이블, 차트 페이지 추가
  src/main/java/com/yum/yumyums/controller/APIController.java
  src/main/java/com/yum/yumyums/controller/DashBoardController.java
  src/main/java/com/yum/yumyums/repository/seller/MenuRepository.java
  src/main/java/com/yum/yumyums/service/DashBoardService.java
  src/main/java/com/yum/yumyums/service/DashBoardServiceImpl.java
  src/main/resources/static/js/dashboard/analysis.js
  src/main/resources/templates/dashboard/analysis.html
Labels: 💻Feature, Plz review, Plz Accept

#72 🚨 hotfix: ImagesDTO NullPointerException 관련 수정
  src/main/java/com/yum/yumyums/dto/ImagesDTO.java
  src/main/java/com/yum/yumyums/dto/seller/StoreDTO.java
Labels: 🐞Hotfix, Plz Accept

#76 챗 봇, faq 검색 기능 추가
  src/main/java/com/yum/yumyums/controller/ChatController.java
  src/main/resources/pyProject/app.py
  src/main/resources/pyProject/logic/deleteMongo.py
  src/main/resources/pyProject/logic/insertMongo.py
  src/main/resources/pyProject/logic/srcAns.py
  src/main/resources/pyProject/logic/srcAnsList.py
  src/main/resources/pyProject/templates/index.html
  src/main/resources/static/js/chat/chat.js
  src/main/resources/static/js/faq/faq.js
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/faq/list.html
Labels: Plz review, Plz Accept

#77 멤버 회원가입시 프로필이미지 등록 기능 추가
  .gitignore
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/dto/user/MemberDTO.java
  src/main/java/com/yum/yumyums/entity/user/Member.java
  src/main/java/com/yum/yumyums/service/user/MemberServiceImpl.java
  src/main/resources/templates/user/memberSave.html
Labels: Plz Accept

#68 매장용 메뉴리스트, 등록
  src/main/java/com/yum/yumyums/controller/StoreController.java
  src/main/java/com/yum/yumyums/dto/seller/MenuDTO.java
  src/main/java/com/yum/yumyums/entity/seller/Menu.java
  src/main/java/com/yum/yumyums/repository/seller/MenuRepository.java
  src/main/java/com/yum/yumyums/service/seller/MenuService.java
  src/main/java/com/yum/yumyums/service/seller/MenuServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/StoreService.java
  src/main/java/com/yum/yumyums/service/seller/StoreServiceImpl.java
  src/main/resources/static/js/common/images.js
  src/main/resources/templates/dashBoardTemplate.html
  src/main/resources/templates/store/manageMenu/list.html
  src/main/resources/templates/store/save.html
Labels: Plz review, Plz Accept

#74 파티 매칭 기능 제작 및 웹소켓 적용
  src/main/java/com/yum/yumyums/config/WebSocketConfig.java
  src/main/java/com/yum/yumyums/controller/MatchController.java
  src/main/java/com/yum/yumyums/controller/PartyController.java
  src/main/java/com/yum/yumyums/controller/PartyMatchController.java
  src/main/java/com/yum/yumyums/dto/chat/MatchRequestDTO.java
  src/main/java/com/yum/yumyums/dto/chat/PartyDTO.java
  src/main/java/com/yum/yumyums/dto/chat/PartyMatchWebSocketMessageDTO.java
  src/main/java/com/yum/yumyums/entity/chat/Party.java
  src/main/java/com/yum/yumyums/repository/chat/PartyMemberRepository.java
  src/main/java/com/yum/yumyums/repository/chat/PartyRepository.java
  src/main/java/com/yum/yumyums/service/chat/PartyService.java
  src/main/java/com/yum/yumyums/service/chat/PartyServiceImpl.java
  src/main/resources/static/js/party/findStore.js
  src/main/resources/static/js/party/main.js
  src/main/resources/static/js/party/partyDetail.js
  src/main/resources/static/js/party/partyMatch.js
  src/main/resources/templates/party/create_party.html
  src/main/resources/templates/party/party_detail.html
  src/main/resources/templates/party/party_home.html
  src/main/resources/templates/party/party_match.html
  src/test/java/com/yum/yumyums/service/chat/PartyServiceImplTest.java
Labels: Plz review, Plz Accept

#80 판매자 페이지 버그수정
  src/main/java/com/yum/yumyums/controller/ChatController.java
  src/main/java/com/yum/yumyums/controller/DashBoardController.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersRepository.java
  src/main/java/com/yum/yumyums/repository/review/ReviewRepository.java
  src/main/java/com/yum/yumyums/service/DashBoardServiceImpl.java
  src/main/resources/static/js/dashboard/analysis.js
  src/main/resources/templates/chat/test.html
  src/main/resources/templates/dashboard/analysis.html
Labels: 🐞Hotfix, Plz review, Plz Accept

#82 판매자대시보드용 헤더
  src/main/resources/static/img/logo_400.png
  src/main/resources/static/img/logo_40_20.png
  src/main/resources/templates/dashBoardTemplate.html
  src/main/resources/templates/inc/dashBoardHeader.html
Labels: Plz Accept

#83 대시보드헤더 경로 수정
  src/main/resources/templates/inc/dashBoardHeader.html
Labels: 🐞Hotfix

#86 장바구니 기능
  src/main/java/com/yum/yumyums/controller/CartController.java
  src/main/java/com/yum/yumyums/controller/OrdersController.java
  src/main/java/com/yum/yumyums/controller/RecommendController.java
  src/main/java/com/yum/yumyums/dto/orders/CartDTO.java
  src/main/java/com/yum/yumyums/dto/orders/OrdersDTO.java
  src/main/java/com/yum/yumyums/dto/orders/OrdersDetailDTO.java
  src/main/java/com/yum/yumyums/dto/seller/StoreDTO.java
  src/main/java/com/yum/yumyums/entity/orders/Cart.java
  src/main/java/com/yum/yumyums/entity/orders/Orders.java
  src/main/java/com/yum/yumyums/entity/orders/OrdersDetail.java
  src/main/java/com/yum/yumyums/entity/seller/Menu.java
  src/main/java/com/yum/yumyums/entity/user/Member.java
  src/main/java/com/yum/yumyums/repository/orders/CartRepository.java
  src/main/java/com/yum/yumyums/repository/review/ReviewRepository.java
  src/main/java/com/yum/yumyums/repository/seller/MenuRepository.java
  src/main/java/com/yum/yumyums/service/orders/CartService.java
  src/main/java/com/yum/yumyums/service/orders/CartServiceImpl.java
  src/main/java/com/yum/yumyums/service/orders/OrdersService.java
  src/main/java/com/yum/yumyums/service/orders/OrdersServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/MenuService.java
  src/main/java/com/yum/yumyums/service/seller/MenuServiceImpl.java
  src/main/resources/templates/carts/cart.html
  src/main/resources/templates/menu/detail.html
  src/main/resources/templates/menu/list.html
  src/main/resources/templates/orders/checkout.html
  src/main/resources/templates/orders/success.html
Labels: Plz review, Plz Accept

#91 Menu관련 class 공동 사용으로 인한 method 중복 현상
  src/main/java/com/yum/yumyums/dto/orders/OrdersDetailDTO.java
  src/main/java/com/yum/yumyums/entity/seller/Menu.java
  src/main/java/com/yum/yumyums/service/seller/MenuService.java
  src/main/java/com/yum/yumyums/service/seller/MenuServiceImpl.java
Labels: Plz review, Plz Accept

#88 매장등록: 다음주소api 및 카카오맵 api 연동
  src/main/java/com/yum/yumyums/controller/StoreController.java
  src/main/java/com/yum/yumyums/dto/seller/StoreDTO.java
  src/main/java/com/yum/yumyums/entity/seller/Store.java
  src/main/resources/static/js/common/maps.js
  src/main/resources/templates/store/save.html
Labels: Plz review, Plz Accept

#89 메인헤더 추가
  src/main/resources/static/img/yumyums_logo.png
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/inc/spinner.html
  src/main/resources/templates/template.html
Labels: Plz review, Plz Accept

#93 메뉴 카테고리 수정
  src/main/java/com/yum/yumyums/controller/RecommendController.java
  src/main/java/com/yum/yumyums/repository/seller/MenuRepository.java
  src/main/java/com/yum/yumyums/service/seller/MenuService.java
  src/main/java/com/yum/yumyums/service/seller/MenuServiceImpl.java
  src/main/resources/templates/carts/cart.html
  src/main/resources/templates/menu/list.html
Labels: Plz Accept

#96 지도 탐색 페이지
  src/main/java/com/yum/yumyums/controller/APIController.java
  src/main/java/com/yum/yumyums/controller/MapController.java
  src/main/java/com/yum/yumyums/controller/RecommendController.java
  src/main/java/com/yum/yumyums/repository/seller/StoreRepository.java
  src/main/java/com/yum/yumyums/service/seller/StoreService.java
  src/main/java/com/yum/yumyums/service/seller/StoreServiceImpl.java
  src/main/resources/static/img/cart-page-header-img.jpg
  src/main/resources/static/js/maps/maps.js
  src/main/resources/static/js/user/address.js
  src/main/resources/templates/map/maps.html
  src/main/resources/templates/store/save.html
  src/main/resources/templates/template.html
Labels: Plz review, Plz Accept

#94 헤더 수정 및 파티페이지 수정
  src/main/resources/static/css/party/party_main.css
  src/main/resources/static/css/style.css
  src/main/resources/static/js/party/checkCreateParty.js
  src/main/resources/static/js/party/main.js
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/party/create_party.html
  src/main/resources/templates/party/join_party.html
  src/main/resources/templates/party/party_detail.html
  src/main/resources/templates/party/party_home.html
  src/main/resources/templates/party/party_match.html
  src/main/resources/templates/template.html
Labels: Plz review, Plz Accept

#98 장바구니 수량 업데이트 기능 수정
  src/main/java/com/yum/yumyums/controller/RecommendController.java
  src/main/java/com/yum/yumyums/service/seller/MenuService.java
  src/main/java/com/yum/yumyums/service/seller/MenuServiceImpl.java
  src/main/resources/static/js/cart/cart.js
  src/main/resources/static/js/menu/detail.js
  src/main/resources/static/js/menu/menu.js
  src/main/resources/templates/carts/cart.html
  src/main/resources/templates/menu/detail.html
  src/main/resources/templates/menu/list.html
  src/main/resources/templates/template.html
Labels: 🐞Hotfix, Plz Accept

#97 파티 메뉴 추가 및 알럿 제작
  src/main/java/com/yum/yumyums/controller/CartController.java
  src/main/java/com/yum/yumyums/controller/RecommendController.java
  src/main/java/com/yum/yumyums/dto/orders/CartDTO.java
  src/main/java/com/yum/yumyums/entity/orders/PartyCart.java
  src/main/java/com/yum/yumyums/repository/orders/PartyCartRepository.java
  src/main/java/com/yum/yumyums/service/orders/CartService.java
  src/main/java/com/yum/yumyums/service/orders/CartServiceImpl.java
  src/main/resources/static/js/alert.js
  src/main/resources/static/js/menu/detail.js
  src/main/resources/static/js/party/partyDetail.js
  src/main/resources/templates/menu/detail.html
  src/main/resources/templates/party/party_detail.html
Labels: Plz review, in progress

#104 로그인 유효성 인터셉터
  src/main/java/com/yum/yumyums/config/MemberInterConfig.java
  src/main/java/com/yum/yumyums/config/SellerInterConfig.java
  src/main/java/com/yum/yumyums/config/StoreInterConfig.java
  src/main/java/com/yum/yumyums/controller/HomeController.java
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/controller/SellerController.java
  src/main/java/com/yum/yumyums/controller/StoreController.java
  src/main/java/com/yum/yumyums/interceptor/MemberInterceptor.java
  src/main/java/com/yum/yumyums/interceptor/SellerInterceptor.java
  src/main/java/com/yum/yumyums/interceptor/StoreInterceptor.java
  src/main/java/com/yum/yumyums/util/SessionUtil.java
  src/main/resources/templates/store/list.html
  src/main/resources/templates/user/login.html
Labels: Plz review, Plz Accept

#105 파티 메뉴추가 중복체크
  src/main/java/com/yum/yumyums/repository/orders/PartyCartRepository.java
  src/main/java/com/yum/yumyums/service/orders/CartServiceImpl.java
Labels: Plz Accept

#107 채팅 맴버 리스트 출력 수정
  src/main/java/com/yum/yumyums/controller/APIController.java
  src/main/java/com/yum/yumyums/controller/ChatController.java
  src/main/java/com/yum/yumyums/dto/chat/ChatMessageDTO.java
  src/main/java/com/yum/yumyums/entity/chat/ChatMessage.java
  src/main/resources/static/css/chat/chat.css
  src/main/resources/static/js/chat/chat.js
  src/main/resources/static/js/faq/faq.js
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/faq/list.html
  src/main/resources/templates/template.html
Labels: Plz review, Plz Accept

#106 로그인화면 탭 CSS
  src/main/java/com/yum/yumyums/controller/HomeController.java
  src/main/resources/templates/template.html
  src/main/resources/templates/user/login.html
Labels: Plz review, Plz Accept

#109 회원가입 진입 페이지 프론트 수정
  src/main/resources/static/img/member_join_1.jpg
  src/main/resources/static/img/member_join_2.jpg
  src/main/resources/static/img/seller_join_1.jpg
  src/main/resources/static/img/seller_join_2.jpg
  src/main/resources/templates/user/join.html
  src/main/resources/templates/user/login.html
Labels: Plz Accept

#110 로그인 탭 클릭시 드롭다운 메뉴 사라지는 에러.
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/user/login.html
Labels: 🐞Hotfix, Plz Accept

#111 회원가입 페이지 배너 추가
  src/main/resources/templates/user/join.html
  src/main/resources/templates/user/memberSave.html
  src/main/resources/templates/user/sellerSave.html
Labels: Plz Accept

#113 주문, 결제 템플릿 적용
  src/main/java/com/yum/yumyums/controller/OrdersController.java
  src/main/java/com/yum/yumyums/repository/seller/MenuRepository.java
  src/main/resources/static/js/orders/orders.js
  src/main/resources/templates/menu/list.html
  src/main/resources/templates/orders/checkout.html
  src/main/resources/templates/orders/success.html
  src/main/resources/templates/user/login.html
Labels: Plz Accept

#114 대시보드 기능 추가
  src/main/java/com/yum/yumyums/controller/DashBoardController.java
  src/main/java/com/yum/yumyums/dto/ImagesDTO.java
  src/main/java/com/yum/yumyums/entity/seller/Store.java
  src/main/java/com/yum/yumyums/repository/ImagesRepository.java
  src/main/java/com/yum/yumyums/service/ImagesService.java
  src/main/java/com/yum/yumyums/service/ImagesServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/StoreService.java
  src/main/java/com/yum/yumyums/service/seller/StoreServiceImpl.java
  src/main/resources/static/js/dashboard/dashboard.js
  src/main/resources/templates/dashboard/analysis.html
  src/main/resources/templates/dashboard/index.html
Labels: Plz review, Plz Accept

#117 인덱스 페이지.
  src/main/resources/static/img/banner_chart.png
  src/main/resources/static/img/banner_chat.png
  src/main/resources/static/img/banner_maps.png
  src/main/resources/static/img/banner_menu.png
  src/main/resources/static/img/banner_party.png
  src/main/resources/static/img/banner_seller.png
  src/main/resources/static/img/banner_store.png
  src/main/resources/static/img/hero-img.jpg
  src/main/resources/static/img/member_join.jpg
  src/main/resources/static/img/member_join_1.jpg
  src/main/resources/static/img/member_join_2.jpg
  src/main/resources/static/img/seller_join.jpg
  src/main/resources/static/img/seller_join_1.jpg
  src/main/resources/static/img/seller_join_2.jpg
  src/main/resources/templates/index.html
  src/main/resources/templates/user/join.html
Labels: Plz Accept

#116 파티 장바구니
  src/main/java/com/yum/yumyums/APIGateway.java
  src/main/java/com/yum/yumyums/config/MemberInterConfig.java
  src/main/java/com/yum/yumyums/controller/CartController.java
  src/main/java/com/yum/yumyums/controller/PartyCartController.java
  src/main/java/com/yum/yumyums/entity/seller/Menu.java
  src/main/java/com/yum/yumyums/repository/orders/PartyCartRepository.java
  src/main/java/com/yum/yumyums/service/chat/PartyServiceImpl.java
  src/main/java/com/yum/yumyums/service/orders/CartService.java
  src/main/java/com/yum/yumyums/service/orders/CartServiceImpl.java
  src/main/resources/static/js/cart/partyCart.js
  src/main/resources/static/js/menu/detail.js
  src/main/resources/templates/carts/party_cart.html
  src/main/resources/templates/menu/detail.html
  src/main/resources/templates/template.html
Labels: Plz review, Plz Accept

#119 메뉴필터 수정
  src/main/java/com/yum/yumyums/controller/RecommendController.java
  src/main/java/com/yum/yumyums/repository/seller/MenuRepository.java
  src/main/java/com/yum/yumyums/service/seller/MenuService.java
  src/main/java/com/yum/yumyums/service/seller/MenuServiceImpl.java
  src/main/resources/static/js/faq/faq.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/menu/menu.js
  src/main/resources/static/js/orders/orders.js
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/menu/detail.html
  src/main/resources/templates/menu/list.html
Labels: Plz Accept

#122 파티주문 홈 css 스타일 적용
  src/main/resources/templates/party/party_home.html
Labels: Plz Accept

#124 회원가입form 페이지 진입시 로그인 유효성 추가, 인덱스 css 추가 수정
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/controller/SellerController.java
  src/main/resources/templates/index.html
Labels: 🐞Hotfix, Plz Accept

#126 마이페이지-단골매장 페이지
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/repository/seller/StoreLikeRepository.java
  src/main/java/com/yum/yumyums/service/seller/StoreService.java
  src/main/java/com/yum/yumyums/service/seller/StoreServiceImpl.java
  src/main/resources/templates/myPage/favorites.html
  src/main/resources/templates/store/list.html
Labels: Plz Accept

#127 사용자의 필터 선택 항목 화면 잔류
  src/main/java/com/yum/yumyums/controller/RecommendController.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersDetailRepository.java
  src/main/java/com/yum/yumyums/service/seller/MenuService.java
  src/main/java/com/yum/yumyums/service/seller/MenuServiceImpl.java
  src/main/resources/static/js/menu/detail.js
  src/main/resources/static/js/menu/menu.js
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/menu/list.html
Labels: Plz Accept

#133 주문완료 시 예상 대기시간 출력
  src/main/java/com/yum/yumyums/controller/OrdersController.java
  src/main/java/com/yum/yumyums/controller/RecommendController.java
  src/main/java/com/yum/yumyums/entity/orders/Orders.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersDetailRepository.java
  src/main/java/com/yum/yumyums/repository/seller/MenuRepository.java
  src/main/java/com/yum/yumyums/service/orders/OrdersService.java
  src/main/java/com/yum/yumyums/service/orders/OrdersServiceImpl.java
  src/main/resources/static/js/orders/orders.js
  src/main/resources/templates/orders/checkout.html
  src/main/resources/templates/orders/success.html
Labels: Plz Accept

#130 헤더 수정 & 대시보드-매장 나가기 추가
  src/main/java/com/yum/yumyums/controller/DashBoardController.java
  src/main/java/com/yum/yumyums/controller/StoreController.java
  src/main/resources/templates/inc/dashBoardHeader.html
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/store/list.html
Labels: Plz Accept

#138 모달 에러 수정
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/chat/addRoom.html
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/index.html
  src/main/resources/templates/template.html
Labels: 🐞Hotfix, Plz review, Plz Accept

#141 pr 날아간것 복구
  src/main/java/com/yum/yumyums/controller/OrdersController.java
  src/main/java/com/yum/yumyums/controller/RecommendController.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersDetailRepository.java
  src/main/java/com/yum/yumyums/repository/seller/MenuRepository.java
  src/main/java/com/yum/yumyums/service/orders/OrdersService.java
  src/main/java/com/yum/yumyums/service/orders/OrdersServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/MenuServiceImpl.java
  src/main/resources/static/js/orders/orders.js
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/menu/list.html
  src/main/resources/templates/orders/checkout.html
  src/main/resources/templates/orders/success.html
Labels: Plz Accept

#146 각종 오류 전면 수정
  src/main/java/com/yum/yumyums/repository/seller/MenuRepository.java
  src/main/java/com/yum/yumyums/service/seller/MenuServiceImpl.java
  src/main/resources/static/js/cart/cart.js
  src/main/resources/static/js/menu/detail.js
  src/main/resources/static/js/menu/menu.js
  src/main/resources/static/js/orders/orders.js
  src/main/resources/templates/carts/cart.html
  src/main/resources/templates/menu/detail.html
  src/main/resources/templates/menu/list.html
  src/main/resources/templates/orders/checkout.html
  src/main/resources/templates/orders/success.html
Labels: Plz Accept

#144 자주가는 지역 검색 모달창 에러 수정
  src/main/resources/templates/user/addStation.html
Labels: 🐞Hotfix, Plz Accept

#142 파티 CSS 수정, 각종 버그 수정, 신규페이지 추가 및 예상대기시간 처리
  src/main/java/com/yum/yumyums/controller/OrdersController.java
  src/main/java/com/yum/yumyums/controller/PartyController.java
  src/main/java/com/yum/yumyums/service/orders/OrdersService.java
  src/main/java/com/yum/yumyums/service/orders/OrdersServiceImpl.java
  src/main/resources/static/js/party/findStore.js
  src/main/resources/templates/inc/header.html
  src/main/resources/templates/party/before_join_party.html
  src/main/resources/templates/party/create_party.html
  src/main/resources/templates/party/join_party.html
  src/main/resources/templates/party/party_detail.html
  src/main/resources/templates/party/party_home.html
  src/main/resources/templates/party/party_home_have_party.html
  src/main/resources/templates/party/party_invite.html
  src/main/resources/templates/party/party_match.html
Labels: Plz review, Plz Accept

#143 마이페이지- 주문내역 페이지
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/dto/orders/OrdersDTO.java
  src/main/java/com/yum/yumyums/dto/orders/OrdersDetailDTO.java
  src/main/java/com/yum/yumyums/dto/orders/OrdersStatusDTO.java
  src/main/java/com/yum/yumyums/entity/orders/Orders.java
  src/main/java/com/yum/yumyums/entity/orders/OrdersStatus.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersRepository.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersStatusRepository.java
  src/main/java/com/yum/yumyums/repository/review/ReviewRepository.java
  src/main/java/com/yum/yumyums/service/orders/OrdersService.java
  src/main/java/com/yum/yumyums/service/orders/OrdersServiceImpl.java
  src/main/resources/templates/myPage/favorites.html
  src/main/resources/templates/myPage/myOrders.html
  src/main/resources/templates/user/addStation.html
Labels: Plz review, Plz Accept

#145 판매자가입 - 사업자등록번호 api
  src/main/resources/templates/user/sellerSave.html
Labels: Plz Accept

#150 chat 버튼 top 버튼 스타일 수정 , 매장목록&매장추가 페이지 배너 추가
  src/main/java/com/yum/yumyums/service/orders/OrdersServiceImpl.java
  src/main/resources/templates/index.html
  src/main/resources/templates/menu/list.html
  src/main/resources/templates/store/list.html
  src/main/resources/templates/store/save.html
  src/main/resources/templates/template.html
Labels: Plz Accept

#152 주문시 주문상태 업데이트
  src/main/java/com/yum/yumyums/service/orders/OrdersServiceImpl.java
Labels: Plz Accept

#156 디폴트이미지 업데이트, 기타 Css 수정
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/controller/StoreController.java
  src/main/java/com/yum/yumyums/service/ImagesServiceImpl.java
  src/main/java/com/yum/yumyums/util/ImageDefaultUrl.java
  src/main/resources/static/css/style.css
  src/main/resources/static/img/yumyums_default.jpg
  src/main/resources/static/img/yumyums_member.jpg
  src/main/resources/static/img/yumyums_menu.jpg
  src/main/resources/static/img/yumyums_store.jpg
  src/main/resources/templates/store/list.html
  src/main/resources/templates/store/manageMenu/list.html
  src/main/resources/templates/store/save.html
  src/main/resources/templates/user/memberSave.html
Labels: Plz Accept

#159 단골매장 등록과 단골매장 취소 기능 추가
  src/main/java/com/yum/yumyums/config/MemberInterConfig.java
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/controller/RecommendController.java
  src/main/java/com/yum/yumyums/repository/seller/StoreLikeRepository.java
  src/main/java/com/yum/yumyums/service/seller/StoreService.java
  src/main/java/com/yum/yumyums/service/seller/StoreServiceImpl.java
  src/main/resources/static/js/alert.js
  src/main/resources/templates/menu/detail.html
Labels: Plz Accept

#163 긴급수정 ! 진짜 긴급!!!
  src/main/resources/templates/menu/detail.html
  src/main/resources/templates/myPage/favorites.html
Labels: 🐞Hotfix, Plz Accept

#167 정식 서버 개설 전 에러 수정 작업
  src/main/java/com/yum/yumyums/controller/DashBoardController.java
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/controller/SellerController.java
  src/main/resources/application.yml
  src/main/resources/pyProject/__pycache__/app.cpython-311.pyc
  src/main/resources/pyProject/logic/__pycache__/srcAns.cpython-311.pyc
  src/main/resources/pyProject/logic/__pycache__/srcAnsList.cpython-311.pyc
  src/main/resources/pyProject/logic/insertMongo.py
  src/main/resources/pyProject/logic/srcAns.py
  src/main/resources/pyProject/logic/srcAnsList.py
  src/main/resources/templates/user/memberSave.html
  src/test/java/com/yum/yumyums/service/chat/PartyServiceImplTest.java
  src/test/java/com/yum/yumyums/service/user/SearchServiceImplTest.java
Labels: 🐞Hotfix, Plz Accept
