Repository j-seon/yumyums, pull requests merged in 2024-07, with the labels that each got.

#5 엔티티 생성
  src/main/java/com/yum/yumyums/entity/Faq.java
  src/main/java/com/yum/yumyums/entity/chat/Chat.java
  src/main/java/com/yum/yumyums/entity/chat/ChatMember.java
  src/main/java/com/yum/yumyums/entity/chat/ChatMessage.java
  src/main/java/com/yum/yumyums/entity/chat/Party.java
  src/main/java/com/yum/yumyums/entity/offerdeal/Offer.java
  src/main/java/com/yum/yumyums/entity/offerdeal/Offerdeal.java
  src/main/java/com/yum/yumyums/entity/orders/Cart.java
  src/main/java/com/yum/yumyums/entity/orders/Orders.java
  src/main/java/com/yum/yumyums/entity/orders/OrdersDetail.java
  src/main/java/com/yum/yumyums/entity/orders/OrdersMember.java
  src/main/java/com/yum/yumyums/entity/orders/OrdersStatus.java
  src/main/java/com/yum/yumyums/entity/review/HashTag.java
  src/main/java/com/yum/yumyums/entity/review/Reply.java
  src/main/java/com/yum/yumyums/entity/review/Review.java
  src/main/java/com/yum/yumyums/entity/seller/Discount.java
  src/main/java/com/yum/yumyums/entity/seller/Menu.java
  src/main/java/com/yum/yumyums/entity/seller/Seller.java
  src/main/java/com/yum/yumyums/entity/seller/Store.java
  src/main/java/com/yum/yumyums/entity/seller/TradingStatus.java
  src/main/java/com/yum/yumyums/entity/timedeal/Timedeal.java
  src/main/java/com/yum/yumyums/entity/timedeal/TimedealOrders.java
  src/main/java/com/yum/yumyums/entity/user/MarkStation.java
  src/main/java/com/yum/yumyums/entity/user/Member.java
  src/main/java/com/yum/yumyums/entity/user/PointList.java
  src/main/java/com/yum/yumyums/entity/user/PresetDetail.java
  src/main/java/com/yum/yumyums/entity/user/SearchFilter.java
  src/main/java/com/yum/yumyums/enums/Busy.java
  src/main/java/com/yum/yumyums/enums/FilterCategory.java
  src/main/java/com/yum/yumyums/enums/FoodCategory.java
  src/main/java/com/yum/yumyums/enums/FoodState.java
  src/main/java/com/yum/yumyums/enums/Gender.java
  src/main/java/com/yum/yumyums/enums/PayType.java
  src/main/resources/application.properties
Labels: Plz Accept

#13 모든 서비스 클레스 제작
  src/main/java/com/yum/yumyums/service/FaqService.java
  src/main/java/com/yum/yumyums/service/FaqServiceImpl.java
  src/main/java/com/yum/yumyums/service/chat/ChatMemberService.java
  src/main/java/com/yum/yumyums/service/chat/ChatMemberServiceImpl.java
  src/main/java/com/yum/yumyums/service/chat/ChatMessageService.java
  src/main/java/com/yum/yumyums/service/chat/ChatMessageServiceImpl.java
  src/main/java/com/yum/yumyums/service/chat/ChatService.java
  src/main/java/com/yum/yumyums/service/chat/ChatServiceImpl.java
  src/main/java/com/yum/yumyums/service/chat/PartyService.java
  src/main/java/com/yum/yumyums/service/chat/PartyServiceImpl.java
  src/main/java/com/yum/yumyums/service/offerdeal/OfferService.java
  src/main/java/com/yum/yumyums/service/offerdeal/OfferServiceImpl.java
  src/main/java/com/yum/yumyums/service/offerdeal/OfferdealService.java
  src/main/java/com/yum/yumyums/service/offerdeal/OfferdealServiceImpl.java
  src/main/java/com/yum/yumyums/service/orders/CartService.java
  src/main/java/com/yum/yumyums/service/orders/CartServiceImpl.java
  src/main/java/com/yum/yumyums/service/orders/OrdersDetailService.java
  src/main/java/com/yum/yumyums/service/orders/OrdersDetailServiceImpl.java
  src/main/java/com/yum/yumyums/service/orders/OrdersMemberService.java
  src/main/java/com/yum/yumyums/service/orders/OrdersMemberServiceImpl.java
  src/main/java/com/yum/yumyums/service/orders/OrdersService.java
  src/main/java/com/yum/yumyums/service/orders/OrdersServiceImpl.java
  src/main/java/com/yum/yumyums/service/orders/OrdersStatusService.java
  src/main/java/com/yum/yumyums/service/orders/OrdersStatusServiceImpl.java
  src/main/java/com/yum/yumyums/service/review/HashTagService.java
  src/main/java/com/yum/yumyums/service/review/HashTagServiceImpl.java
  src/main/java/com/yum/yumyums/service/review/ReplyService.java
  src/main/java/com/yum/yumyums/service/review/ReplyServiceImpl.java
  src/main/java/com/yum/yumyums/service/review/ReviewService.java
  src/main/java/com/yum/yumyums/service/review/ReviewServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/DiscountService.java
  src/main/java/com/yum/yumyums/service/seller/DiscountServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/MenuService.java
  src/main/java/com/yum/yumyums/service/seller/MenuServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/SellerService.java
  src/main/java/com/yum/yumyums/service/seller/SellerServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/StoreService.java
  src/main/java/com/yum/yumyums/service/seller/StoreServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/TradingStatusService.java
  src/main/java/com/yum/yumyums/service/seller/TradingStatusServiceImpl.java
  src/main/java/com/yum/yumyums/service/timedeal/TimedealOrdersService.java
  src/main/java/com/yum/yumyums/service/timedeal/TimedealOrdersServiceImpl.java
  src/main/java/com/yum/yumyums/service/timedeal/TimedealService.java
  src/main/java/com/yum/yumyums/service/timedeal/TimedealServiceImpl.java
  src/main/java/com/yum/yumyums/service/user/MarkStationService.java
  src/main/java/com/yum/yumyums/service/user/MarkStationServiceImpl.java
  src/main/java/com/yum/yumyums/service/user/MemberService.java
  src/main/java/com/yum/yumyums/service/user/MemberServiceImpl.java
  src/main/java/com/yum/yumyums/service/user/PointListService.java
  src/main/java/com/yum/yumyums/service/user/PointListServiceImpl.java
  src/main/java/com/yum/yumyums/service/user/PresetDetailService.java
  src/main/java/com/yum/yumyums/service/user/PresetDetailServiceImpl.java
  src/main/java/com/yum/yumyums/service/user/SearchFilterService.java
  src/main/java/com/yum/yumyums/service/user/SearchFilterServiceImpl.java
Labels: Plz Accept

#14 DTO 생성
  build.gradle
  src/main/java/com/yum/yumyums/YumyumsApplication.java
  src/main/java/com/yum/yumyums/dto/FaqDTO.java
  src/main/java/com/yum/yumyums/dto/TemplateData.java
  src/main/java/com/yum/yumyums/dto/chat/ChatDTO.java
  src/main/java/com/yum/yumyums/dto/chat/ChatMemberDTO.java
  src/main/java/com/yum/yumyums/dto/chat/ChatMessageDTO.java
  src/main/java/com/yum/yumyums/dto/chat/PartyDTO.java
  src/main/java/com/yum/yumyums/dto/offerdeal/OfferDTO.java
  src/main/java/com/yum/yumyums/dto/offerdeal/OfferdealDTO.java
  src/main/java/com/yum/yumyums/dto/orders/CartDTO.java
  src/main/java/com/yum/yumyums/dto/orders/OrdersDTO.java
  src/main/java/com/yum/yumyums/dto/orders/OrdersDetailDTO.java
  src/main/java/com/yum/yumyums/dto/orders/OrdersMemberDTO.java
  src/main/java/com/yum/yumyums/dto/orders/OrdersStatusDTO.java
  src/main/java/com/yum/yumyums/dto/review/HashTagDTO.java
  src/main/java/com/yum/yumyums/dto/review/ReplyDTO.java
  src/main/java/com/yum/yumyums/dto/review/ReviewDTO.java
  src/main/java/com/yum/yumyums/dto/seller/DiscountDTO.java
  src/main/java/com/yum/yumyums/dto/seller/MenuDTO.java
  src/main/java/com/yum/yumyums/dto/seller/SellerDTO.java
  src/main/java/com/yum/yumyums/dto/seller/StoreDTO.java
  src/main/java/com/yum/yumyums/dto/seller/TradingStatusDTO.java
  src/main/java/com/yum/yumyums/dto/timedeal/TimedealDTO.java
  src/main/java/com/yum/yumyums/dto/timedeal/TimedealOrdersDTO.java
  src/main/java/com/yum/yumyums/dto/user/MarkStationDTO.java
  src/main/java/com/yum/yumyums/dto/user/MemberDTO.java
  src/main/java/com/yum/yumyums/dto/user/PointListDTO.java
  src/main/java/com/yum/yumyums/dto/user/PresetDetailDTO.java
  src/main/java/com/yum/yumyums/dto/user/SearchFilterDTO.java
Labels: Plz Accept

#15 Controller 및 Repository 생성
  src/main/java/com/yum/yumyums/controller/ChatController.java
  src/main/java/com/yum/yumyums/controller/OfferdealController.java
  src/main/java/com/yum/yumyums/controller/OrdersController.java
  src/main/java/com/yum/yumyums/controller/ReviewController.java
  src/main/java/com/yum/yumyums/controller/SellerController.java
  src/main/java/com/yum/yumyums/controller/TimedealController.java
  src/main/java/com/yum/yumyums/controller/UserController.java
  src/main/java/com/yum/yumyums/repository/FaqRepository.java
  src/main/java/com/yum/yumyums/repository/chat/ChatMemberRepository.java
  src/main/java/com/yum/yumyums/repository/chat/ChatMessageRepository.java
  src/main/java/com/yum/yumyums/repository/chat/ChatRepository.java
  src/main/java/com/yum/yumyums/repository/chat/PartyRepository.java
  src/main/java/com/yum/yumyums/repository/offerdeal/OfferRepository.java
  src/main/java/com/yum/yumyums/repository/offerdeal/OfferdealRepository.java
  src/main/java/com/yum/yumyums/repository/orders/CartRepository.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersDetailRepository.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersMemberRepository.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersRepository.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersStatusRepository.java
  src/main/java/com/yum/yumyums/repository/review/HashTagRepository.java
  src/main/java/com/yum/yumyums/repository/review/ReplyRepository.java
  src/main/java/com/yum/yumyums/repository/review/ReviewRepository.java
  src/main/java/com/yum/yumyums/repository/seller/DiscountRepository.java
  src/main/java/com/yum/yumyums/repository/seller/MenuRepository.java
  src/main/java/com/yum/yumyums/repository/seller/SellerRepository.java
  src/main/java/com/yum/yumyums/repository/seller/StoreRepository.java
  src/main/java/com/yum/yumyums/repository/seller/TradingStatusRepository.java
  src/main/java/com/yum/yumyums/repository/timedeal/TimedealOrdersRepository.java
  src/main/java/com/yum/yumyums/repository/timedeal/TimedealRepository.java
  src/main/java/com/yum/yumyums/repository/user/MarkStationRepository.java
  src/main/java/com/yum/yumyums/repository/user/MemberRepository.java
  src/main/java/com/yum/yumyums/repository/user/PointListRepository.java
  src/main/java/com/yum/yumyums/repository/user/PresetDetailRepository.java
  src/main/java/com/yum/yumyums/repository/user/SearchFilterRepository.java
Labels: Plz review, Plz Accept

#17 설정파일 복구 #16
  build.gradle
  src/main/java/com/yum/yumyums/YumyumsApplication.java
Labels: Plz Accept

#18 Fix controllers and repositories
  build.gradle
  src/main/java/com/yum/yumyums/controller/ChatController.java
  src/main/java/com/yum/yumyums/controller/OfferdealController.java
  src/main/java/com/yum/yumyums/controller/OrdersController.java
  src/main/java/com/yum/yumyums/controller/ReviewController.java
  src/main/java/com/yum/yumyums/controller/SellerController.java
  src/main/java/com/yum/yumyums/controller/TimedealController.java
  src/main/java/com/yum/yumyums/controller/UserController.java
  src/main/java/com/yum/yumyums/repository/FaqRepository.java
  src/main/java/com/yum/yumyums/repository/chat/ChatMemberRepository.java
  src/main/java/com/yum/yumyums/repository/chat/ChatMessageRepository.java
  src/main/java/com/yum/yumyums/repository/chat/ChatRepository.java
  src/main/java/com/yum/yumyums/repository/chat/PartyRepository.java
  src/main/java/com/yum/yumyums/repository/offerdeal/OfferRepository.java
  src/main/java/com/yum/yumyums/repository/offerdeal/OfferdealRepository.java
  src/main/java/com/yum/yumyums/repository/orders/CartRepository.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersDetailRepository.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersMemberRepository.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersRepository.java
  src/main/java/com/yum/yumyums/repository/orders/OrdersStatusRepository.java
  src/main/java/com/yum/yumyums/repository/review/HashTagRepository.java
  src/main/java/com/yum/yumyums/repository/review/ReplyRepository.java
  src/main/java/com/yum/yumyums/repository/review/ReviewRepository.java
  src/main/java/com/yum/yumyums/repository/seller/DiscountRepository.java
  src/main/java/com/yum/yumyums/repository/seller/MenuRepository.java
  src/main/java/com/yum/yumyums/repository/seller/SellerRepository.java
  src/main/java/com/yum/yumyums/repository/seller/StoreRepository.java
  src/main/java/com/yum/yumyums/repository/seller/TradingStatusRepository.java
  src/main/java/com/yum/yumyums/repository/timedeal/TimedealOrdersRepository.java
  src/main/java/com/yum/yumyums/repository/timedeal/TimedealRepository.java
  src/main/java/com/yum/yumyums/repository/user/MarkStationRepository.java
  src/main/java/com/yum/yumyums/repository/user/MemberRepository.java
  src/main/java/com/yum/yumyums/repository/user/PointListRepository.java
  src/main/java/com/yum/yumyums/repository/user/PresetDetailRepository.java
  src/main/java/com/yum/yumyums/repository/user/SearchFilterRepository.java
Labels: Plz Accept

#20 참고용 MVC패턴 CRUD 추가
  src/main/java/com/yum/yumyums/dto/TemplateData.java
  src/main/java/com/yum/yumyums/entity/seller/Discount.java
  src/main/java/com/yum/yumyums/entity/seller/TradingStatus.java
  src/main/java/com/yum/yumyums/entity/timedeal/TimedealOrders.java
  src/main/java/com/yum/yumyums/ref/controllerRef/RefController.java
  src/main/java/com/yum/yumyums/ref/dtoRef/RefDTO.java
  src/main/java/com/yum/yumyums/ref/dtoRef/RefTemplateData.java
  src/main/java/com/yum/yumyums/ref/entityRef/BaseRefEntity.java
  src/main/java/com/yum/yumyums/ref/entityRef/RefEntity.java
  src/main/java/com/yum/yumyums/ref/repositoryRef/RefRepository.java
  src/main/java/com/yum/yumyums/ref/serviceRef/RefService.java
  src/main/java/com/yum/yumyums/repository/seller/DiscountRepository.java
  src/main/java/com/yum/yumyums/repository/seller/TradingStatusRepository.java
  src/main/java/com/yum/yumyums/repository/timedeal/TimedealOrdersRepository.java
  src/main/resources/templates/inc/alert.html
  src/main/resources/templates/inc/alertRef.html
  src/main/resources/templates/index.html
  src/main/resources/templates/ref/detail.html
  src/main/resources/templates/ref/list.html
  src/main/resources/templates/ref/save.html
  src/main/resources/templates/ref/update.html
  src/main/resources/templates/template.html
  src/main/resources/templates/templateRef.html
Labels: Plz review, Plz Accept

#21 참고용 Spring MVC 패턴에 RESTful 구조 적극 활용하기 위한 전면 수정!
  src/main/java/com/yum/yumyums/board/controller/BoardController.java
  src/main/java/com/yum/yumyums/board/controller/HomeController.java
  src/main/java/com/yum/yumyums/board/dto/BoardDTO.java
  src/main/java/com/yum/yumyums/board/entity/BaseEntity.java
  src/main/java/com/yum/yumyums/board/entity/BoardEntity.java
  src/main/java/com/yum/yumyums/board/repository/BoardRepository.java
  src/main/java/com/yum/yumyums/board/service/BoardService.java
  src/main/java/com/yum/yumyums/dto/TemplateData.java
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/ex.html
  src/main/resources/templates/board/list.html
  src/main/resources/templates/board/save.html
  src/main/resources/templates/board/update.html
  src/main/resources/templates/inc/alert.html
  src/main/resources/templates/inc/alertRef.html
  src/main/resources/templates/index.html
  src/main/resources/templates/ref/detail.html
  src/main/resources/templates/ref/list.html
  src/main/resources/templates/ref/save.html
  src/main/resources/templates/ref/update.html
  src/main/resources/templates/template.html
  src/main/resources/templates/templateRef.html
Labels: Plz Accept

#34 파티 컨트롤러 버그 수정
  src/main/java/com/yum/yumyums/controller/PartyController.java
Labels: 🐞Hotfix, Plz Accept

#26 일반회원가입 페이지
  build.gradle
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/controller/UserController.java
  src/main/java/com/yum/yumyums/dto/user/MarkStationDTO.java
  src/main/java/com/yum/yumyums/dto/user/MemberDTO.java
  src/main/java/com/yum/yumyums/entity/user/MarkStation.java
  src/main/java/com/yum/yumyums/entity/user/Member.java
  src/main/java/com/yum/yumyums/enums/Gender.java
  src/main/java/com/yum/yumyums/service/user/MemberService.java
  src/main/java/com/yum/yumyums/service/user/MemberServiceImpl.java
  src/main/resources/templates/user/memberSave.html
Labels: Plz Accept

#36 로그인 & 로그아웃 기능
  src/main/java/com/yum/yumyums/controller/HomeController.java
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/controller/SellerController.java
  src/main/java/com/yum/yumyums/reference/controller/HomeController.java
  src/main/java/com/yum/yumyums/service/seller/SellerService.java
  src/main/java/com/yum/yumyums/service/seller/SellerServiceImpl.java
  src/main/java/com/yum/yumyums/service/user/MemberService.java
  src/main/java/com/yum/yumyums/service/user/MemberServiceImpl.java
  src/main/resources/templates/index.html
  src/main/resources/templates/user/login.html
Labels: Plz Accept

#39 컨트롤러, 서비스 버그수정
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/controller/SellerController.java
  src/main/java/com/yum/yumyums/service/FaqService.java
  src/main/java/com/yum/yumyums/service/user/MemberServiceImpl.java
Labels: 🐞Hotfix, Plz Accept

#41 로그인 긴급수정 !
  src/main/resources/templates/user/login.html
Labels: 🐞Hotfix, Plz Accept

#42 멤버 회원가입 이메일인증 기능 추가
  src/main/java/com/yum/yumyums/controller/EmailController.java
  src/main/java/com/yum/yumyums/service/EmailService.java
  src/main/java/com/yum/yumyums/service/FaqService.java
  src/main/java/com/yum/yumyums/service/user/EmailServiceImpl.java
  src/main/resources/templates/template.html
  src/main/resources/templates/user/memberSave.html
Labels: Plz review

#43 공용 유틸서비스 개발
  src/main/java/com/yum/yumyums/APIGateway.java
  src/main/java/com/yum/yumyums/vo/SecureUtil.java
  src/main/java/com/yum/yumyums/vo/SessionUtil.java
Labels: Plz review

#44 유틸 수정사항 반영
  src/main/java/com/yum/yumyums/vo/SessionUtil.java
Labels: Plz Accept

#46 지하철역정보 api 연동
  build.gradle
  src/main/java/com/yum/yumyums/controller/HomeController.java
  src/main/java/com/yum/yumyums/controller/StationController.java
  src/main/java/com/yum/yumyums/dto/StationDTO.java
  src/main/java/com/yum/yumyums/entity/Station.java
  src/main/java/com/yum/yumyums/repository/StationRepository.java
  src/main/java/com/yum/yumyums/service/StationService.java
  src/main/java/com/yum/yumyums/service/StationServiceImpl.java
  src/main/resources/templates/index.html
Labels: Plz review

#47 일반회원가입 내 지하철역 검색 및 자주가는 지역 등록
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/controller/StationController.java
  src/main/java/com/yum/yumyums/dto/user/MarkStationDTO.java
  src/main/java/com/yum/yumyums/dto/user/MemberDTO.java
  src/main/java/com/yum/yumyums/dto/user/MemberJoinRequest.java
  src/main/java/com/yum/yumyums/entity/user/MarkStation.java
  src/main/java/com/yum/yumyums/entity/user/Member.java
  src/main/java/com/yum/yumyums/repository/StationRepository.java
  src/main/java/com/yum/yumyums/service/StationService.java
  src/main/java/com/yum/yumyums/service/StationServiceImpl.java
  src/main/java/com/yum/yumyums/service/user/MemberService.java
  src/main/java/com/yum/yumyums/service/user/MemberServiceImpl.java
  src/main/resources/templates/user/addStation.html
  src/main/resources/templates/user/memberSave.html
Labels: Plz review

#48 판매자 회원가입 이메일 인증
  src/main/java/com/yum/yumyums/controller/EmailController.java
  src/main/java/com/yum/yumyums/service/user/EmailService.java
  src/main/java/com/yum/yumyums/service/user/EmailServiceImpl.java
  src/main/resources/static/js/user/emailVerification.js
  src/main/resources/templates/template.html
  src/main/resources/templates/user/addStation.html
  src/main/resources/templates/user/memberSave.html
  src/main/resources/templates/user/sellerSave.html
Labels: Plz review, Plz Accept

#37 파티생성
  src/main/java/com/yum/yumyums/APIGateway.java
  src/main/java/com/yum/yumyums/controller/APIController.java
  src/main/java/com/yum/yumyums/controller/PartyController.java
  src/main/java/com/yum/yumyums/controller/SearchController.java
  src/main/java/com/yum/yumyums/dto/chat/PartyDTO.java
  src/main/java/com/yum/yumyums/dto/chat/PartyMemberDTO.java
  src/main/java/com/yum/yumyums/dto/seller/StoreDTO.java
  src/main/java/com/yum/yumyums/entity/chat/Party.java
  src/main/java/com/yum/yumyums/entity/chat/PartyMember.java
  src/main/java/com/yum/yumyums/entity/seller/Store.java
  src/main/java/com/yum/yumyums/enums/FixUrl.java
  src/main/java/com/yum/yumyums/enums/FoodCategory.java
  src/main/java/com/yum/yumyums/enums/PayType.java
  src/main/java/com/yum/yumyums/enums/RandomType.java
  src/main/java/com/yum/yumyums/repository/chat/PartyMemberRepository.java
  src/main/java/com/yum/yumyums/repository/chat/PartyRepository.java
  src/main/java/com/yum/yumyums/repository/seller/StoreRepository.java
  src/main/java/com/yum/yumyums/repository/user/MemberRepository.java
  src/main/java/com/yum/yumyums/repository/user/SearchRepository.java
  src/main/java/com/yum/yumyums/service/chat/PartyService.java
  src/main/java/com/yum/yumyums/service/chat/PartyServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/StoreService.java
  src/main/java/com/yum/yumyums/service/seller/StoreServiceImpl.java
  src/main/java/com/yum/yumyums/service/user/MemberService.java
  src/main/java/com/yum/yumyums/service/user/MemberServiceImpl.java
  src/main/java/com/yum/yumyums/service/user/SearchService.java
  src/main/java/com/yum/yumyums/service/user/SearchServiceImpl.java
  src/main/java/com/yum/yumyums/util/PKGenerator.java
  src/main/java/com/yum/yumyums/util/SecureUtil.java
  src/main/java/com/yum/yumyums/util/SessionUtil.java
  src/main/resources/static/css/party/party_main.css
  src/main/resources/static/js/party/main.js
  src/main/resources/templates/party/create_party.html
  src/main/resources/templates/party/join_party.html
  src/main/resources/templates/party/party_detail.html
  src/main/resources/templates/party/party_home.html
  src/main/resources/templates/party/party_invite.html
  src/test/java/com/yum/yumyums/service/chat/PartyServiceImplTest.java
  src/test/java/com/yum/yumyums/service/user/SearchServiceImplTest.java
Labels: Plz review, Plz Accept

#49 지하철역 검색을 위한 APIController 추가
  src/main/java/com/yum/yumyums/controller/APIController.java
  src/main/java/com/yum/yumyums/controller/StationController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/user/addStation.html
  src/main/resources/templates/user/memberSave.html
Labels: Plz review, Plz Accept

#52 메소드를 찾을 수 없는 에러해결
  src/main/java/com/yum/yumyums/dto/chat/PartyMemberDTO.java
  src/main/java/com/yum/yumyums/service/chat/PartyServiceImpl.java
Labels: 🐞Hotfix, Plz Accept

#55 웹소켓을 이용한 채팅 기능 추가
  build.gradle
  gradlew
  src/main/java/com/yum/yumyums/config/WebSocketConfig.java
  src/main/java/com/yum/yumyums/controller/ChatController.java
  src/main/java/com/yum/yumyums/dto/chat/ChatDTO.java
  src/main/java/com/yum/yumyums/dto/chat/ChatMemberDTO.java
  src/main/java/com/yum/yumyums/dto/chat/ChatMessageDTO.java
  src/main/java/com/yum/yumyums/entity/chat/Chat.java
  src/main/java/com/yum/yumyums/entity/chat/ChatMember.java
  src/main/java/com/yum/yumyums/entity/chat/ChatMessage.java
  src/main/java/com/yum/yumyums/repository/chat/ChatMemberRepository.java
  src/main/java/com/yum/yumyums/repository/chat/ChatMessageRepository.java
  src/main/java/com/yum/yumyums/repository/user/MemberRepository.java
  src/main/java/com/yum/yumyums/service/chat/ChatMemberService.java
  src/main/java/com/yum/yumyums/service/chat/ChatMemberServiceImpl.java
  src/main/java/com/yum/yumyums/service/chat/ChatMessageService.java
  src/main/java/com/yum/yumyums/service/chat/ChatMessageServiceImpl.java
  src/main/java/com/yum/yumyums/service/chat/ChatService.java
  src/main/java/com/yum/yumyums/service/chat/ChatServiceImpl.java
  src/main/java/com/yum/yumyums/service/user/MemberService.java
  src/main/java/com/yum/yumyums/service/user/MemberServiceImpl.java
  src/main/resources/static/css/chat/chat.css
  src/main/resources/static/css/common/bootstrap-icons@1.4.1.css
  src/main/resources/static/css/common/bs.css
  src/main/resources/static/css/common/fontawesome.css
  src/main/resources/static/css/common/googlefont.css
  src/main/resources/static/js/chat/chat.js
  src/main/resources/static/js/chat/sockjs.js
  src/main/resources/static/js/chat/stomp.js
  src/main/resources/static/js/common/bs.js
  src/main/resources/static/js/common/jquery.js
  src/main/resources/static/js/common/popper.js
  src/main/resources/templates/chat/chat.html
  src/main/resources/templates/faq/list.html
  src/main/resources/templates/template.html
Labels: 💻Feature, Plz review, Plz Accept

#56 카카오 지도 api키 받아오기
  src/main/java/com/yum/yumyums/controller/MapController.java
  src/main/java/com/yum/yumyums/controller/RecommendController.java
  src/main/java/com/yum/yumyums/dto/orders/CartDTO.java
  src/main/java/com/yum/yumyums/entity/seller/StoreLike.java
  src/main/java/com/yum/yumyums/repository/seller/MenuRepository.java
  src/main/java/com/yum/yumyums/service/seller/MenuServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/StoreService.java
  src/main/java/com/yum/yumyums/service/seller/StoreServiceImpl.java
  src/main/resources/templates/map/address.html
Labels: Plz Accept

#58 접속한 판매자의 매장 목록과 선택 매장 로그인 구현
  src/main/java/com/yum/yumyums/controller/MemberController.java
  src/main/java/com/yum/yumyums/controller/SellerController.java
  src/main/java/com/yum/yumyums/controller/StoreController.java
  src/main/java/com/yum/yumyums/dto/seller/StoreDTO.java
  src/main/java/com/yum/yumyums/repository/seller/StoreLikeRepository.java
  src/main/java/com/yum/yumyums/repository/seller/StoreRepository.java
  src/main/java/com/yum/yumyums/service/StationServiceImpl.java
  src/main/java/com/yum/yumyums/service/seller/StoreService.java
  src/main/java/com/yum/yumyums/service/seller/StoreServiceImpl.java
  src/main/resources/templates/index.html
  src/main/resources/templates/store/list.html
  src/main/resources/templates/template.html
Labels: Plz review, Plz Accept

#60 매장 추가하기 및 매장명 중복검사
  src/main/java/com/yum/yumyums/controller/APIController.java
  src/main/java/com/yum/yumyums/controller/StoreController.java
  src/main/java/com/yum/yumyums/dto/seller/StoreDTO.java
  src/main/java/com/yum/yumyums/service/seller/StoreService.java
  src/main/java/com/yum/yumyums/service/seller/StoreServiceImpl.java
  src/main/resources/static/js/common/duplicate.js
  src/main/resources/templates/store/list.html
  src/main/resources/templates/store/save.html
  src/main/resources/templates/template.html
Labels: Plz review

#57 파티원 목록보기, 파티초대, 파티탈퇴
  src/main/java/com/yum/yumyums/YumyumsApplication.java
  src/main/java/com/yum/yumyums/controller/PartyController.java
  src/main/java/com/yum/yumyums/dto/chat/PartyDTO.java
  src/main/java/com/yum/yumyums/dto/chat/PartyMemberDTO.java
  src/main/java/com/yum/yumyums/entity/chat/Party.java
  src/main/java/com/yum/yumyums/entity/chat/PartyMember.java
  src/main/java/com/yum/yumyums/repository/chat/PartyMemberRepository.java
  src/main/java/com/yum/yumyums/repository/chat/PartyRepository.java
  src/main/java/com/yum/yumyums/service/chat/PartyService.java
  src/main/java/com/yum/yumyums/service/chat/PartyServiceImpl.java
  src/main/resources/static/css/party/party_detail.css
  src/main/resources/static/css/party/party_main.css
  src/main/resources/static/img/invate-party.png
  src/main/resources/static/js/party/beforeJoinParty.js
  src/main/resources/static/js/party/main.js
  src/main/resources/static/js/party/partyDetail.js
  src/main/resources/templates/inc/redirect.html
  src/main/resources/templates/party/before_join_party.html
  src/main/resources/templates/party/create_party.html
  src/main/resources/templates/party/join_party.html
  src/main/resources/templates/party/party_detail.html
Labels: Plz review, Plz Accept
